version: '3'

services:
  db:
    image: postgres:14
    container_name: shop-java-docker
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shop
      POSTGRES_PORT: 5432
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-data:
    driver: local