version: '3'

services:
  backend:
    build: .
    image: shop-java-web-app
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shop #postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - spring-postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_PASSWORD=admin
    expose:
      - 5432
volumes:
  db-data:
networks:
  spring-postgres: